version: "3.3"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: marko_dev
    ports:
      - "7432:5432"
    volumes:
      - ./.postgres-data/:/var/lib/postgresql/data
